### ISSUE TITLE
Executable does not work for Windows

### ISSUE THREAD

**Issue by umutcakan** [humaine-anac/application#3]
Hey there,

I have tried to download & install the latest executable for windows. But I got the following error when I try to run it from the command line as humaine-win.exe

**internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '\snapshot\build\modules'
[90m    at Object.readdirSync (fs.js:854:3)[39m
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:832:35)
    at Object.<anonymous> (C:\snapshot\build\bin.js:12:22)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:813:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:14)[39m
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
[90m    at internal/main/run_main_module.js:17:11[39m {
  errno: [33m-4058[39m,
  syscall: [32m'scandir'[39m,
  code: [32m'ENOENT'[39m,
  path: [32m'\\snapshot\\build\\modules'[39m
}**

After getting this error, I have downloaded the zip version and tried to run **node generate.json**. There are also 3 issues that I have faced and partially solved:

1.  rm -rf command in generate.json -> Does not work for windows for sure, commanded it out.
2.  Line 52 -> execSync(`node_modules/.bin/pkg --out-path ${dist_dir} --targets ${targets} build`);
On this line it throws out the error cannot find node_modules, so I figured it out in Windows you have to type the full path to execute files.
3. After getting executable from the generate.json, same error occurs as above when I have tried to run it.

I am not familiar with node that much, so I will appreciate if you can help me.

**Comment by MasterOdin** [comment]
A new build is being generated that should work on Windows. I've also resolved the various path issues you pointed out here. Once the build is generated, and I've tested things on Windows and Linux to make sure nothing broke, will close this issue.

**Comment by MasterOdin** [comment]
New generated build: https://github.com/humaine-anac/application/releases/tag/20200325184139

**Comment by umutcakan** [comment]
Thank you so much, it seems it is working now :)
